decent install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,77 +2,58 @@
 
 VERSION=0.1.6
 
-rm hcephes-$VERSION.tar.gz >/dev/null 2>&1 || true
-rm -rf hcephes-$VERSION >/dev/null 2>&1 /dev/null || true
+function silent_run
+{
+    eval "$@ >/dev/null 2>&1"
+}
 
-FILE=$VERSION.tar.gz
+function silent_trun
+{
+    eval "$@ >/dev/null 2>&1 || true"
+}
 
-echo -n "Downloading hcephes-$FILE..."
-curl -o hcephes-$VERSION.tar.gz \
-     -L https://github.com/limix/hcephes/archive/$FILE \
-     >/dev/null 2>&1
-if [[ "$?" == "0" ]]; then
-    echo " done."
-else
-    echo " FAILED."
-    exit 1
-fi
-
-tar xzf hcephes-$FILE
-cd hcephes-$VERSION
-
-mkdir build
-cd build
-
-echo -n "Compiling..."
-cmake .. >/dev/null 2>&1
-make >/dev/null 2>&1
-if [[ "$?" == "0" ]]; then
-    echo " done."
-else
-    echo " FAILED."
-    exit 1
-fi
-
-echo -n "Testing..."
-make test >/dev/null 2>&1
-if [[ "$?" == "0" ]]; then
-    echo " done."
-else
-    echo " FAILED."
-    exit 1
-fi
-
-echo -n "Installing..."
-if loc="$(type -p "sudo")" || [ -z "$loc" ]; then
-    sudo make install >/dev/null 2>&1
-    if [[ "$?" != "0" ]]; then
-        make install >/dev/null 2>&1
+function do_then_sudo
+{
+    eval "$@"
+    if [ $? != 0 ]; then
+        eval "sudo $@"
     fi
-else
-    make install >/dev/null 2>&1
-fi
-if [[ "$?" == "0" ]]; then
-    echo " done."
-else
-    echo " FAILED."
-    exit 1
-fi
+}
 
-cd ..
-cd ..
+FILE=hcephes-$VERSION.tar.gz
+DIR=hcephes-$VERSION
+URL=https://github.com/limix/hcephes/archive/$VERSION.tar.gz
 
-rm hcephes-$VERSION.tar.gz >/dev/null 2>&1 || true
-rm -rf hcephes-$VERSION >/dev/null 2>&1 || true
+silent_trun rm $FILE
+silent_trun rm -rf $DIR
+
+echo -n "[1/5] Downloading... "
+silent_run curl -o $FILE -L $URL
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+
+tar xzf $FILE && cd $DIR
+mkdir build && cd build
+
+echo -n "[2/5] Configuring... "
+silent_run cmake ..
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+
+echo -n "[3/5] Compiling... "
+silent_run make
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+
+echo -n "[4/5] Testing... "
+silent_run make test
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+
+echo -n "[5/5] Installing... "
+silent_run do_then_sudo make install
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+
+cd .. && cd ..
+silent_trun rm hcephes-$VERSION.tar.gz
+silent_trun rm -rf hcephes-$VERSION
 
 if type "ldconfig" >/dev/null; then
-    if loc="$(type -p "sudo")" || [ -z "$loc" ]; then
-        sudo ldconfig >/dev/null 2>&1
-        if [[ "$?" != "0" ]]; then
-            ldconfig >/dev/null 2>&1
-        fi
-    else
-        ldconfig
-    fi
+    silent_run do_then_sudo ldconfig
 fi
-
